### ISSUE TITLE
Possible mapping changes for GB 18030

### ISSUE THREAD

**Issue by eisoch** [eisoch/irg#27]
|GB 18030|Char.|Former UCS|After UCS|G Ref.|
| -- | -- | -- | -- | -- |
|0xFE51|𠂇|U+E816|U+20087|G9-FE51|
|0xFE52|𠂉|U+E817|U+20089|G9-FE52|
|0xFE53|𠃌|U+E818|U+200CC|G9-FE53|
|0xFE6C|𡗗|U+E831|U+215D7|G9-FE6C|
|0xFE76|𢦏|U+E83B|U+2298F|G9-FE76|
|0xFE91|𤇾|U+E855|U+241FE|G9-FE91|
|0x95329031||U+20087|U+E816|PUA|
|0x95329033||U+20089|U+E817|PUA|
|0x95329730||U+200CC|U+E818|PUA|
|0x9534B431|N/A|U+20BC7|Unknown|Unknown|
|0x9536B937||U+215D7|U+E831|PUA|
|0x9630BA35||U+2298F|U+E83B|PUA|
|0x9635B630||U+241FE|U+E855|PUA|
|0x96398E38|N/A|U+25426|Unknown|Unknown|
|Unknown|𠯇|Unknown|U+20BC7|N/A|
|Unknown|𥐦|Unknown|U+25426|N/A|

**Comment by mrhso** [comment]
我认为对于 PUA 的迁移，涉及 non-BMP 还需要进行考量。
因为一般对于 GB 18030 的转换，non-BMP 是采用公式运算，那么进行置换可能会破坏算法。

**Comment by eisoch** [comment]
Closed
