### ISSUE TITLE
U+35F4(㗴) & U+232BA(𣊺)

### ISSUE THREAD

**Issue by eisoch** [eisoch/irg#30]
J4-2442 glyph for U+35F4(㗴) is duplicate with U+232BA(𣊺). 
![image](https://user-images.githubusercontent.com/24350864/37549990-3c81e99c-29c1-11e8-89f5-2fc48ca057bd.png)
![image](https://user-images.githubusercontent.com/24350864/37550000-5919615c-29c1-11e8-9269-9343ad335e09.png)

**Comment by hfhchan** [comment]
上口下日

**Comment by eisoch** [comment]
𠯭？ @hfhchan

**Comment by hfhchan** [comment]
左邊部首都唔同

**Comment by eisoch** [comment]
IDS误导
