### ISSUE TITLE
V4-477E glyph for U+2BE4A has not matched the evidence

### ISSUE THREAD

**Issue by eisoch** [eisoch/irg#51]
The current IDS for U+2BE4A is ⿰𢪒𢒎
![image](https://user-images.githubusercontent.com/24350864/48675025-56dce280-eb8e-11e8-802e-ff36eca77a54.png)
The corresponding evidence in IRGN1564. 
![image](https://user-images.githubusercontent.com/24350864/48675049-9d324180-eb8e-11e8-88d2-278fca0fd7a5.png)
This character means "to fly" and the left component is 拜 not 𢪒. 𢪒 is the variant of 廾, and the right component of 拜 is not 手 very clearly. 
The source of the Vietnamese word for U+2BE4A should be 飛 because of 古無清唇音. 
And Vietnam submits the variant of U+2BE4A to WS2017, which the SN is 00216.

**Comment by hfhchan** [comment]
![image](https://user-images.githubusercontent.com/8191296/91723489-69db6e00-ebce-11ea-94bb-28f48037bdf6.png)
Unicode v13.0
