### ISSUE TITLE
The ref. for U+2B089 should be updated

### ISSUE THREAD

**Issue by eisoch** [eisoch/irg#62]
![image](https://user-images.githubusercontent.com/24350864/54170400-82733800-44b1-11e9-824c-35519301ff84.png)
I found out the new evidence and explanation in the article 《汕头话读本》的方言用字 written by 黄淑芬. 
![image](https://user-images.githubusercontent.com/24350864/54170444-b5b5c700-44b1-11e9-81fa-20772ae0c52f.png)
It's better to change the ref. to UTC-nnnnn.

**Comment by kenlunde** [comment]
@eisoch I am not sure whether a UCI → UTC source prefix change requires a horizontal extension (probably not), but you should give John a heads up anyway, especially because IRG N2369 is likely to be discussed during IRG52 in May.

**Comment by eisoch** [comment]
> @eisoch I am not sure whether a UCI → UTC source prefix change requires a horizontal extension (probably not), but you should give John a heads up anyway, especially because IRG N2369 is likely to be discussed during IRG52 in May.

done. thanks. ;-)
